### ISSUE TITLE
Build errors with latest pico sdk 2.0.0

### ISSUE THREAD

**Issue by fhoedemakers** [shuichitakano/pico_lib#10]
Hi,

There is a new version for the Pico SDK available: 2.0.0. I want to switch to this version because i want to develop also for the RP2350. (Still waiting for my Pico 2 to be delivered)
 
However, building  pico_lib using this latest SDK fails.
![Schermafbeelding 2024-08-29 om 04 11 48](https://github.com/user-attachments/assets/cd31e669-cada-4553-a9e6-42483063772c)

I could make it build and work again using the changes below:

In dvi.cpp the include **<hardware/structs/padsbank0.h>** must be added (works in all versions of the SDK):

![image](https://github.com/user-attachments/assets/bf2dd442-e0e4-41c0-81ce-3c439a691334)

In dma.cpp at line 149, a field name in a struct is probably renamed from **tcr** to **dbg_tcr**:

![image](https://github.com/user-attachments/assets/04af7f0d-d3bb-48a3-817e-7790d2d3fa1f)

The executable builded with these changes works fine.

If those changes are ok by you, i'll create a pull request for pico_lib

Additionally, the CMakeLists.txt in the  [pico-infones](https://github.com/shuichitakano/pico-infones) project at line 33 needs to change from

family_configure_target(picones)

to

family_configure_target(picones "")

Best regards,

Frank

**Comment by shuichitakano** [comment]
Thank you!
I believe the corrections you proposed are accurate, so I would appreciate it if you could create a Pull Request.

**Comment by fhoedemakers** [comment]
Thanks for merging!
